## Tensor Operations


In [1]:
import torch 
import numpy 
import torch.nn.functional as F


## Bring the index that match a specific element

In [3]:
a, b = 10, 0

a, b = torch.tensor([a]), torch.tensor([b])




In [4]:
x = torch.tensor([[ 9,  6,  5,  4, 10],
                  [ 8,  7,  3,  5,  5],
                  [ 4,  9, 10, 10, 10],
                  [10,  9,  7, 10,  2]])

x

tensor([[ 9,  6,  5,  4, 10],
        [ 8,  7,  3,  5,  5],
        [ 4,  9, 10, 10, 10],
        [10,  9,  7, 10,  2]])

In [5]:
x_ = torch.cat([x, a.repeat(x.size(0))[:, None]], axis=1)

x_

tensor([[ 9,  6,  5,  4, 10, 10],
        [ 8,  7,  3,  5,  5, 10],
        [ 4,  9, 10, 10, 10, 10],
        [10,  9,  7, 10,  2, 10]])

In [8]:
bp_=torch.stack([torch.cat([xi[:bpi], b, xi[bpi:]]) for xi, bpi in zip(x, bp)])
bp_

tensor([[ 9,  6,  5,  4,  0, 10],
        [ 8,  7,  3,  5,  5,  0],
        [ 4,  9,  0, 10, 10, 10],
        [ 0, 10,  9,  7, 10,  2]])

## Find the first occurance of the element 

In [11]:

bp = (x_ == a).int().argmax(axis=1)
bp

tensor([4, 5, 2, 0])

## This will insert 0 just before 1st 10

In [12]:
bp_=torch.stack([torch.cat([xi[:bpi], b, xi[bpi:]]) for xi, bpi in zip(x, bp)])
bp_

tensor([[ 9,  6,  5,  4,  0, 10],
        [ 8,  7,  3,  5,  5,  0],
        [ 4,  9,  0, 10, 10, 10],
        [ 0, 10,  9,  7, 10,  2]])

## Appending an int to a specific index


In [13]:
x = torch.ones(1,4)
index = torch.tensor([0])
a = x.index_fill_(1, index, -1)
a

tensor([[-1.,  1.,  1.,  1.]])

## Outer product between two tensors preserving the batch size 

In [17]:
x = torch.Tensor([[1,6, 5, 4]])
y = torch.Tensor([[1,3, 2, 1]])

bs_x, x_dim = x.shape
bs_y, y_dim = y.shape

outer_product = (x.view(bs_x, 1, x_dim) * y.view(bs_y, y_dim, 1))
print(outer_product.numpy())
print(outer_product.shape)

[[[ 1.  6.  5.  4.]
  [ 3. 18. 15. 12.]
  [ 2. 12. 10.  8.]
  [ 1.  6.  5.  4.]]]
torch.Size([1, 4, 4])


## Expand a tensor and assign a value to that index


In [26]:
a = torch.tensor([[1,2,3,4,5,6,7,8,9,10,11,12,13,14]])
b = torch.tensor([[0]])
print(a.shape)

torch.Size([1, 14])


In [29]:
x =torch.cat((a,b.expand((1,1))),dim=1)
print(x.numpy())

x = torch.roll(x, 1)
x
print(x.numpy())

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14  0]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


## Convert a 2D tensor with shape (3, 4) to a 3D tensor with shape (3, 4, 1)

In [23]:
x = torch.randn(3, 4)
x = x[:, :, None]
x.shape

torch.Size([3, 4, 1])

## Convert a 1D tensor with shape (1) to a 3D tensor with shape (1, 1, 16) 

In [24]:
x = torch.randn(16)
x = x[None, None]
x.shape

torch.Size([1, 1, 16])

## Re-shaping tensors using the -1 

In [10]:
x = torch.arange(6)
x

tensor([0, 1, 2, 3, 4, 5])

In [16]:

print(x.view(3, -1)) # inferred size will be 2 as 6 / 3 = 2
print(x.view(3, -1).shape) # inferred size will be 2 as 6 / 3 = 2

tensor([[0, 1],
        [2, 3],
        [4, 5]])
torch.Size([3, 2])


In [4]:
print(x.view(-1, 6))      # inferred size will be 1 as 6 / 6 = 1


tensor([[0, 1, 2, 3, 4, 5]])


In [15]:
print(x.view(1, -1, 2))   # inferred size will be 3 as 6 / (1 * 2) = 3
# tensor([[[ 0.,  1.],
#          [ 2.,  3.],
#          [ 4.,  5.]]])
print(x.view(1, -1, 2).shape)   # inferred size will be 3 as 6 / (1 * 2) = 3
# tensor([[[ 0.,  1.],
#          [ 2.,  3.],
#          [ 4.,  5.]]])


tensor([[[0, 1],
         [2, 3],
         [4, 5]]])
torch.Size([1, 3, 2])


In [ ]:


# print(x.view(-1, 5))    # throw error as there's no int N so that 5 * N = 6
# RuntimeError: invalid argument 2: size '[-1 x 5]' is invalid for input with 6 elements

print(x.view(-1, -1, 3))  # throw error as only one dimension can be inferred
# RuntimeError: invalid argument 1: only one dimension can be inferred

In [20]:
y = torch.randn(2,64,5,5)

In [42]:
dims = (y.size(0), -1, y.size(2) * x.size(3)) # [2,-1,5*5]
dims

(2, -1, 25)

In [43]:
c = torch.randn(2,17,5,5)
out =c.view(dims)
out.shape

torch.Size([2, 17, 25])

In [166]:
x = torch.randn(2,64,5,5)

### Clone a 1D tnesor to 2D 

In [9]:
x = torch.tensor([1,2,3,4,5])
print('x equals:',x, 'of shape',x.shape)
x_repeate =x.repeat(5,1).T
print('x after cloning cequals:\n',x_repeate, 'of shape',x_repeate.shape)

# access the first raw of the tensor
fst_row = x_repeate[0][0:]
print('\n First row of a tensor x equals:\n',fst_row, 'of shape',fst_row.shape)


x equals: tensor([1, 2, 3, 4, 5]) of shape torch.Size([5])
x after cloning cequals:
 tensor([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5]]) of shape torch.Size([5, 5])

 First row of a tensor x equals:
 tensor([1, 1, 1, 1, 1]) of shape torch.Size([5])
